# -*- coding: utf-8 -*-
# vim: ft=yaml
---
name: Commitlint
'on': [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:comments
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      # yamllint disable-line rule:comments rule:line-length
      - uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed # v6.2.1
